spring:
  application:
    name: vce

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vce
    username: postgres
    password: postgres

  jpa:
    show-sql: true


jwt:
  secret: MTNwVjZlWUQ1OU1Uc2szK2NUdnE2WjZSWVNCWFlBbEFHaTAvMjkyRFk5cVR1TzYxbFd6VDVIYVRXUEtQUnpITFg0ajRiKyt3OFl3WmhEWEhnUkk0M3FPQW9TK24zc093UXgwTm1NNmtwUFlkT094aXA1dFZMbnMzbmU5amZqRENYdzJiVUdHLytBV25xeDN6YkNld3RCM0FlQ2wyYitZbFEybTg4MTVZMHZ1L0lLdkg0Q0RLR0NZdXF0d0NuTVc4VUNtMjJTU2RlMjc4bnlaNVNMQXl3TzE2Z1h6dnl4TE11Ni9tdXFCWnM0WXZSNGNhZk5sWE5EQnBxU21KMGI1WmFhNUhoWjJFaXByRGFlSDNYWm0weVNUY2Qxa05WdERHbjdPT2dWRk9GVWxoUzNtOEFVZkhiaURWVTF5Qm9id2N5Qjl4cHMvNDRsQVJkMzJnRENoYmFQcHdsUXZ0ZkVYSW5maXBLYXVibFpFPQ==
  access:
    expiration: 86400
  refresh:
    expiration: 86400